### ISSUE TITLE
can you convert bag to aedat4?

### ISSUE THREAD

**Issue by ccca1** [jmaiolini/aedat4-to-bag#1]

**Comment by jmaiolini** [comment]
Is this a request?
Currently the script only converts aedat4 to bag files.
However the ROS [wrapper](https://github.com/uzh-rpg/rpg_dvs_ros) for DV should under-the-hood perform the conversion you are looking for.

**Comment by MohamadHalwani** [comment]
I'm trying to convert from bag to aedat4 since hours now. Any luck ?

**Comment by jiejeiz** [comment]
Do you mean that if I want to use your plugin, I need to use it under the condition of another code of yours?
